package com.example.jnisample.toolbox

/**
 * Created by Manne Öhlund on 2019-04-19.
 */

val commandList = listOf(
    "su",
    "printenv",
    "echo \"Hello \$LOGNAME\"",
    "echo \"\$USER\"",
    "whoami",
    "\$(find \$(echo \$(pm list packages -f | cut -d ':' -f2 | grep com.example.jni | egrep -oE '.*\\==')/lib) | grep cwhoami)",
    "cwhoami=\$(find \$(echo \$(pm list packages -f | cut -d ':' -f2 | grep com.example.jni | egrep -oE '.*\\==')/lib) | grep cwhoami)",
    "echo \$cwhoami",
    "\$cwhoami",
    "\$cfind",
    "\$cfind /data/app/ .apk$",
    "\$cfind -i /data/data/ .apk$",
    "\$cfind /data/data/ .so$",
    "\$cfind /sdcard/ .jpg",
    "\$cfind -i /sdcard/ .JPG",
    "\$cfind /sdcard/ 'creen.*.JPG$'",
    "\$cfind /sdcard/ 'screen.*.JPG$'",
    "\$cfind -i /sdcard/ 'creen.*.JPG$'",
    "\$cfind -i /sdcard/ 'screen.*.JPG$'",
    "\$cfind -i /sdcard/ 'screen.*.JPG$'",
    "\$cfind /sdcard/ '.jpg$|.jpeg$|.apk$'",
    "\$cfind -i /sdcard/ '.jpg$|.jpeg$|.apk$'",
    "\$cfind /sdcard/DCIM jpg",
    "\$cfind /sdcard/ screen",
    "\$cfind /sdcard/ SCREEN",
    "\$cfind /sdcard/ Screen",
    "\$cfind /sdcard/ DCIM",
    "\$cfind /data/data/ '[[apk*'",
    "exit",
    "",
    "ps",
    "ps -l",
    "ps -o pid= | grep -E '[0-9]+'",
    "ps -o name= | grep -iE '[a-z]+'",
    "ps -o name= | grep -m1 -iE '[a-z]+'",
    "ps -AZ | grep u0_",
    "ps -AZ | grep u0_ | sed -r 's/[\\t ]+/;/g' | cut -d ';' -f 1",
    "ps -Af -o user -o uid -o pid -o ppid -o name -o s | grep u0_",
    "ps -Af -o user -o uid -o pid -o ppid -o name -o s | grep u0_ | sed -r 's/[\\t ]+/:/g'",
    "ps -Af -o user -o uid -o pid -o ppid -o name -o s | grep u0_ | sed -r 's/[\\t ]+/:/g' | cut -d ':' -f 5",
    "",
    "pm list packages -f",
    "pm list packages -f -U", // file, package, uid
    "pm list packages -f -3",
    "pm list packages -f -s",
    "pm list packages -f | egrep -oE '\\/.*'",
    "pm list packages -f | egrep -oE '\\/.*\\apk'",
    "pm list packages -f | cut -d ':' -f2 | grep com.example.jni | egrep -oE '.*\\=='",
    "pm list packages | cut -d ':' -f2",
    "pm list packages | cut -d ':' -f2 | xargs -0 echo",
    "uid_packagename=$(pm list packages -f -U) && _uid=$(\$uid_packagename cut -d ' ' -f 2) && ",
    "pm list packages -f -U | cut -d ' ' -f 2 | cut -d ':' -f 2", // UID by PACKAGE NAME
    "pm list packages -f -U | grep 'com.spotify.music' | cut -d ' ' -f 2 | cut -d ':' -f 2", // UID by PACKAGE NAME
    "pm list packages -f -U | awk 'BEGIN{FS=\" \"; OFS=\":\"} {print \$1,\$2}' | awk 'BEGIN{FS=\":\"; OFS=\":\"} {print \$2,\$4}' | awk 'BEGIN{FS=\"=\"; OFS=\"\"} {print \$2}' | grep -ie '[\\w]",
    "",
    "uidByPackage() { pm list packages -f -U | grep $1 | cut -d ' ' -f 2 | cut -d ':' -f 2; }",
    "uidByPackage com.spotify.music",
    "",
    "dumpsys package com.example.jnisample | grep version",
    "dumpsys package com.example.jnisample | grep -iE 'codePath=|dataDir='",
    "dumpsys package com.spotify.music | grep -E '.*lastUpdateTime.*|.*firstInstallTime.*|.*version[NC].*|.*\\.permission\\..*'",
    "",
    "du -h -s /data/app/com.example.jnisample-5EUp6qx5KjdCrq0AKcP-jg==",
    "",
    "find /sdcard/ -type f -iname '*screen*'",
    "find /sdcard/ -type f | grep -iE '.*screen.*'",
    "find /sdcard/ -type f | grep -E '.jpg$|.jpeg$|.apk$'",
    "find /sdcard/ -type f | grep -iE '.jpg$|.jpeg$|.apk$'",
    "find /sdcard/ -type f -print0 | grep -ziE '.*screen.*' | xargs -0 stat -c '%A:%U:%G:%n'",
    "find /sdcard/ -type f -print0 | grep -ziE '.*screen.*$' | xargs -0 stat -c '%A:%U:%G:%n'",
    "find /sdcard/ -type f -print0 | grep -ziE '.*screen.*(.png$|.jpg$)' | xargs -0 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "find /sdcard/ -type f -print0 | grep -ziE '.jpg$|.jpeg$|.apk$' | xargs -0 stat -c '%A:%U:%G:%n'",
    "find /sdcard/ -type f -print0 | grep -ziE '.jpg$|.jpeg$|.apk$' | xargs -0 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "find /sdcard/ -type f -print0 | grep -ziE '.jpg|.jpeg|.apk' | xargs -0 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "",
    "find /data -type f -print0 | grep -ziE '.apk$' | xargs -0 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "find /data -type f -print0 | grep -ziE '.*screen.*(.png$|.jpg$)' | xargs -0 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "",
    "find /sdcard/ -type f | egrep -ioE '\\.{1}[a-z]*$'",
    "find /sdcard/ -type f | egrep -ioE '\\.{1}[a-z]*$' | sort | uniq -c | sort -r",
    "",
    "find / -maxdepth 1 -print0 | xargs -0 -n 50 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "find /sdcard/ -print0 | xargs -0 stat -c '%A:%U:%G:%n'",
    "find /sdcard/ -print0 | xargs -0 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "find /sdcard/ -print0 | xargs -0 -n 200 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "find /sdcard/ -maxdepth 1 -print0 | xargs -0 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "find /sdcard/ -mindepth 1 -maxdepth 1 -print0 | xargs -0 stat -c '%A:%f:%i:%u:%G:%X:%Y:%Z:%n'",
    "find /sdcard/DCIM/Camera -maxdepth 1 -print0 | xargs -0 stat -c '%A:%f:%U:%G:%n' | sort -t ':' -k1,1d -k5fd",
    "find /sdcard/DCIM/Camera -maxdepth 1 -print0 | xargs -0 stat -c '%A:%f:%U:%G:%n' | awk 'BEGIN {FS=\"/\"; OFS=\"::\"}{print \$0,\$NF}'| sort -t ':' -k1,1d -k7fd",
    "find /sdcard/ -maxdepth 2 -print0 | xargs -0 stat -c '%A:%f:%U:%G:%n' | awk 'BEGIN {FS=\"/\"; OFS=\"::\"}{print \$0,\$NF}' | sort -t ':' -k1,1dr -k7fd",
    "find /sdcard/ -maxdepth 2 -print0 | xargs -0 stat -c '%A:%f:%U:%G:%n' | awk 'BEGIN {FS=\"/\"; OFS=\"::\"}{print \$0,\$NF}' | sort -t ':' -k1,1dr -k7fd | sed -r 's/::.*\$//g'",
    "find /sdcard/ -maxdepth 2 -print0 | xargs -0 stat -c '%A:%f:%U:%G:%n' | awk 'BEGIN {FS=\"/\"; OFS=\"::\"}{print \$0,\$NF}' | sort -t ':' -k1,1dr -k7fdr",
    "find /sdcard/ -maxdepth 2 -print0 | xargs -0 stat -c '%A:%f:%U:%G:%n' | awk 'BEGIN {FS=\"/\"; OFS=\"::\"}{print \$0,\$NF}' | sort -t ':' -k1,1dr -k7fdr | sed -r 's/::.*\$//g'",
    "find /sdcard/ -maxdepth 2 -print0 | xargs -0 stat -c '%A:%f:%U:%G:%n' | awk 'BEGIN {FS=\"/\"; OFS=\"|\"}{print \$NF,\$0}' | sort -t '|' -k1 | awk -F '|' '{print \$NF}' | sort -t ':' -k1,1d",
    "",
    "stat -c '%u,%U' /proc/uid/*",
    "stat -c '%u,%U:%g,%G' /proc/uid/*",
    "stat -c '%u,(%U):%g,(%G)' /proc/uid/*",
    "",
    "ls -l /",
    "ls -l /sdcard/",
    "ls -lR /sdcard/",
    "",
    "ls -l /data/app",
    "ls -l /data/app/*",
    "ls -l /data/data",
    "ls -l /data/data/$(ps -o name= | grep -m1 -iE '[a-z]+')"
);